version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: marketplace_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    container_name: marketplace_mongo
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: marketplace_redis
    restart: always
    ports:
      - "6379:6379"
